# [START runtime]
runtime: nodejs
env: flex
# [END runtime]

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
 - ^app\.yaml
 - ^README\..*
 - \.gitignore 
 - ^\.git$
 - ^src$
 - ^e2e$
 - \.editorconfig
 - ^karma\.config\.js
 - ^protractor\.conf\.js
 - ^tslint\.json
 - ^tsconfig\.json

