# [START runtime]
runtime: nodejs
env: flex
# [END runtime]

handlers:

- url: /(.+)
  static_files: dist/\1
  upload: dist/(.*)

- url: /
  static_files: dist/index.html
  upload: dist/index.html

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
 - ^app\.yaml
 - ^README\..*
 - \.gitignore 
 - ^\.git$
 - ^src$
 - ^e2e$
 - \.editorconfig
 - ^karma\.config\.js
 - ^package\.json
 - ^protractor\.conf\.js
 - ^tslint\.json
 - ^tsconfig\.json

